# Generated by Django 4.2.1 on 2023-06-07 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Penulis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('usia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Catatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('penerbit', models.CharField(max_length=100)),
                ('pembuat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catatan', to='notes.penulis')),
            ],
        ),
    ]
